development:
  GOOGLE_KEY: "887476207948-a5vldvdin0o94fc19mc8nt3kkidfe3tg.apps.googleusercontent.com"
  GOOGLE_SECRET: "hvZu4a71Y4zaLk82tmYxZIlx"
  TWITTER_KEY: ~
  TWITTER_SECRET: ~
  FACEBOOK_KEY: "347792108716613"
  FACEBOOK_SECRET: "2279e31e99f9a2925f84e7f4170a2d70"
  S3_KEY: "0G9B8JGV31EYF2F1MNG2"
  S3_SECRET: "BpkE3JJrFtTzeLTmt1go4ZRCyJ51sPru9CrTNcXg"
  S3_BUCKET: "iloveu"
  SMTP_DOMAIN: "smtp.mailgun.org"
  SMTP_USERNAME: "postmaster@frisson.io"
  SMTP_PASSWORD: "69d87d918145e49bb2d4a444c4e53c3f"

production:
  GOOGLE_KEY: ~
  GOOGLE_SECRET: ~
  TWITTER_KEY: ~
  TWITTER_SECRET: ~
  FACEBOOK_KEY: ~
  FACEBOOK_SECRET: ~
  S3_KEY: "0G9B8JGV31EYF2F1MNG2"
  S3_SECRET: "BpkE3JJrFtTzeLTmt1go4ZRCyJ51sPru9CrTNcXg"
  S3_BUCKET: "iloveu"
  SMTP_DOMAIN: "smtp.mailgun.org"
  SMTP_USERNAME: "postmaster@frisson.io"
  SMTP_PASSWORD: "69d87d918145e49bb2d4a444c4e53c3f"
